[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sati = "satiRkxEiwZ51cv8PRu8UMzuaqeaNU9jABo6oAFMsLe"

[programs.devnet]
sati = "satiRkxEiwZ51cv8PRu8UMzuaqeaNU9jABo6oAFMsLe"

[programs.mainnet]
sati = "satiRkxEiwZ51cv8PRu8UMzuaqeaNU9jABo6oAFMsLe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
upgradeable = true
startup_wait = 10000

[scripts]
test = "pnpm vitest run tests/smoke/"
